# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'release'

steps:

- task: CmdLine@2
  inputs:
    script: 'tree /a /f'

- task: NuGetToolInstaller@0
  displayName: NuGet Install

- task: NuGetCommand@2
  displayName: NuGet Restore
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Test Solution'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@1
  displayName: 'Build GettingStartedApplication sfpkg'
  inputs:
    solution: '$(Build.SourcesDirectory)/src/GettingStartedApplication/GettingStartedApplication/GettingStartedApplication.sfproj'
    msbuildArgs: '/t:Package'
    platform: x64
    configuration: '$(buildConfiguration)'

- powershell: |
   Compress-Archive -U -Path "*"  -DestinationPath GettingStartedApplication.zip
   Rename-Item GettingStartedApplication.zip GettingStartedApplication.sfpkg
  errorActionPreference: continue
  workingDirectory: '$(Build.SourcesDirectory)/src/GettingStartedApplication/GettingStartedApplication/pkg/Release'
  displayName: 'Create GettingStartedApplication.sfpkg'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/src/GettingStartedApplication/GettingStartedApplication/pkg/Release/GettingStartedApplication.sfpkg'
    ArtifactName: GettingStartedApplication

