# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'release'

resources:
  pipelines:
  - pipeline: build
    source: 'Build - service-fabric-dotnet-getting-started'
    trigger: 
      branches:
      - master

steps:

- task: CmdLine@2
  inputs:
    script: 'tree /a /f'

- task: DownloadPipelineArtifact@2
  inputs:
    source: 'specific'
    artifact: 'GettingStartedApplication'
    project: 'rossdotpink'
    pipeline: 1
    runVersion: 'latestFromBranch'
    runBranch: 'refs/heads/master'
  displayName: 'Download GettingStartedApplication.sfpkg'

- task: CmdLine@2
  inputs:
    script: 'tree /a /f $(System.ArtifactsDirectory)'

- task: ServiceFabricDeploy@1
  inputs:
    applicationPackagePath: '$(System.ArtifactsDirectory)/GettingStartedApplication/GettingStartedApplication.sfpkg'
    serviceConnectionName: 'chama-ross-assessment'